FROM node:17-alpine as build

ENV NODE_ENV local
WORKDIR /app

COPY ./package.json ./yarn.lock ./

COPY ./@app/client/ ./@app/client

COPY ./@app/gql/ ./@app/gql

RUN yarn install --pure-lockfile --non-interactive

CMD ["yarn", "client", "dev"]
