FROM node:17-buster-slim

ENV NODE_ENV local
WORKDIR /app

COPY ./package.json ./yarn.lock ./tsconfig.json ./

COPY ./@app/server/ ./@app/server

RUN yarn install --pure-lockfile --non-interactive

ENTRYPOINT ["yarn", "server", "dev"]
